### ISSUE TITLE
Doesn't work on x86 emulator

### ISSUE THREAD

**Issue by furtherout** [alphacep/kaldi-android-demo#6]
First of all, great repo. Second of all, I had a few problems getting it to run on emulator (works fine on device). FYI I had to modify the project's build.gradle version to:         
`classpath 'com.android.tools.build:gradle:3.5.2' ` to get it to build at all- if you wish I will raise a PR for this.

Here is the output for x86 emulator:

```
11/10 17:53:09: Launching 'Unnamed' on Pixel 3a XL API 28.
$ adb shell am start -n "org.kaldi.demo/org.kaldi.demo.KaldiActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -D
Waiting for application to come online: org.kaldi.demo.test | org.kaldi.demo
Waiting for application to come online: org.kaldi.demo.test | org.kaldi.demo
Waiting for application to come online: org.kaldi.demo.test | org.kaldi.demo
Connecting to org.kaldi.demo
Waiting for application to start debug server
Waiting for application to come online: org.kaldi.demo.test | org.kaldi.demo
Connecting to org.kaldi.demo
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/System.out: Debugger has connected
    waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
Connected to the target VM, address: 'localhost:8606', transport: 'socket'
I/chatty: uid=10091(org.kaldi.demo) identical 3 lines
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/chatty: uid=10091(org.kaldi.demo) identical 1 line
I/System.out: waiting for debugger to settle...
I/System.out: debugger has settled (1451)
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.kaldi.demo, PID: 19763
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.kaldi.demo-SKbwCrrRmi-p28GOnMedrQ==/base.apk"],nativeLibraryDirectories=[/data/app/org.kaldi.demo-SKbwCrrRmi-p28GOnMedrQ==/lib/x86, /system/lib]]] couldn't find "libkaldi_jni.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at org.kaldi.demo.KaldiActivity.<clinit>(KaldiActivity.java:36)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
        at android.support.v4.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:43)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1215)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2831)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Disconnected from the target VM, address: 'localhost:8606', transport: 'socket'
```
Looks like libkaldi_jni.so is missing from inside aars? I haven't looked but would building https://github.com/alphacep/kaldi-android make this work?

**Comment by nshmyrev** [comment]
Should be fixed now in commit ab26c9355a51b2215d9b779329d3264d0297d703, the aar has been updated with the x86 jni. Checkout again and try.

**Comment by furtherout** [comment]
I tried the new commit (double checked that the kaldi-android-5.2.aar has gone from 5.2mb now to 8.6mb). And cleaned the build and app to make sure it's not using a cached version on the device. You never know with Android studio.

Same problem:
```
2019-11-12 22:38:41.529 6250-6250/? I/org.kaldi.demo: Not late-enabling -Xcheck:jni (already on)
2019-11-12 22:38:41.552 6250-6250/? W/org.kaldi.demo: Unexpected CPU variant for X86 using defaults: x86
2019-11-12 22:38:41.577 6250-6257/? E/org.kaldi.demo: Failed to send DDMS packet REAQ to debugger (-1 of 20): Broken pipe
2019-11-12 22:38:41.717 6250-6250/? D/AndroidRuntime: Shutting down VM
2019-11-12 22:38:41.719 6250-6250/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.kaldi.demo, PID: 6250
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.kaldi.demo-P3qhLYCSHTJErqv9EYnO0Q==/base.apk"],nativeLibraryDirectories=[/data/app/org.kaldi.demo-P3qhLYCSHTJErqv9EYnO0Q==/lib/x86, /system/lib]]] couldn't find "libkaldi_jni.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at org.kaldi.demo.KaldiActivity.<clinit>(KaldiActivity.java:36)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
        at android.support.v4.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:43)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1215)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2831)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-11-12 22:41:47.942 6250-6250/org.kaldi.demo I/Process: Sending signal. PID: 6250 SIG: 9
```
I checked that the build/.transforms folder was fresh by actually deleting it. Then resyncing Gradle. Inside the first folder there does appear to be this .so file.

```
$ ~/kaldi-android-demo/aars/build/.transforms/0da90a208aa8dd378cc449971f089024/kaldi-android-5.2/jni$ tree 
├── arm64-v8a
│   └── libkaldi_jni.so
├── armeabi-v7a
│   └── libkaldi_jni.so
└── x86_64
    └── libkaldi_jni.so
```

**Comment by nshmyrev** [comment]
@furtherout Hey, your emulator is 32-bit it seems, you'll have to rebuild it again to get 32-bit. I'm not very passionate to do it honestly, how about you upgrade Android Studio to 64-bits? See https://android-developers.googleblog.com/2019/06/moving-android-studio-and-android.html

**Comment by furtherout** [comment]
Thanks moving to x86_64 emulator is one step closer. the app now opens and requests for mic. however it does still crash. I have checked with another debug app that it's definately 64bit. Here is the log:

```
2019-11-13 10:15:54.666 6011-6011/? I/org.kaldi.demo: Not late-enabling -Xcheck:jni (already on)
2019-11-13 10:15:54.745 6011-6011/? W/org.kaldi.demo: Unexpected CPU variant for X86 using defaults: x86_64
2019-11-13 10:15:54.760 6011-6018/? E/org.kaldi.demo: Failed to send DDMS packet REAQ to debugger (-1 of 20): Broken pipe
2019-11-13 10:15:54.916 6011-6011/? D/OpenGLRenderer: HWUI GL Pipeline
2019-11-13 10:15:55.027 6011-6040/? I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
2019-11-13 10:15:55.028 6011-6040/? I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2019-11-13 10:15:55.028 6011-6040/? I/OpenGLRenderer: Initialized EGL, version 1.4
2019-11-13 10:15:55.028 6011-6040/? D/OpenGLRenderer: Swap behavior 1
2019-11-13 10:15:55.030 6011-6040/? W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
2019-11-13 10:15:55.030 6011-6040/? D/OpenGLRenderer: Swap behavior 0
2019-11-13 10:15:55.041 6011-6040/? D/EGL_emulation: eglCreateContext: 0x78ce6b3ea480: maj 2 min 0 rcv 2
2019-11-13 10:15:55.044 6011-6040/? D/EGL_emulation: eglMakeCurrent: 0x78ce6b3ea480: ver 2 0 (tinfo 0x78ce6b229280)
2019-11-13 10:15:55.163 6011-6040/? D/EGL_emulation: eglMakeCurrent: 0x78ce6b3ea480: ver 2 0 (tinfo 0x78ce6b229280)
2019-11-13 10:16:04.877 6011-6052/org.kaldi.demo I/Assets: Copying asset model-android/ivector/final.dubm to /storage/emulated/0/Android/data/org.kaldi.demo/files/sync/model-android/ivector/final.dubm
2019-11-13 10:16:04.878 6011-6052/org.kaldi.demo I/Assets: Copying asset model-android/ivector/splice.conf to /storage/emulated/0/Android/data/org.kaldi.demo/files/sync/model-android/ivector/splice.conf
2019-11-13 10:16:04.879 6011-6052/org.kaldi.demo I/Assets: Copying asset model-android/ivector/final.mat to /storage/emulated/0/Android/data/org.kaldi.demo/files/sync/model-android/ivector/final.mat
2019-11-13 10:16:04.879 6011-6052/org.kaldi.demo I/Assets: Copying asset model-android/mfcc.conf to /storage/emulated/0/Android/data/org.kaldi.demo/files/sync/model-android/mfcc.conf
2019-11-13 10:16:04.953 6011-6052/org.kaldi.demo I/Assets: Copying asset model-android/HCLr.fst to /storage/emulated/0/Android/data/org.kaldi.demo/files/sync/model-android/HCLr.fst
2019-11-13 10:16:04.963 6011-6052/org.kaldi.demo I/Assets: Copying asset model-android/words.txt to /storage/emulated/0/Android/data/org.kaldi.demo/files/sync/model-android/words.txt
2019-11-13 10:16:04.964 6011-6052/org.kaldi.demo I/Assets: Copying asset model-android/word_boundary.int to /storage/emulated/0/Android/data/org.kaldi.demo/files/sync/model-android/word_boundary.int
2019-11-13 10:16:04.964 6011-6052/org.kaldi.demo I/Assets: Copying asset model-android/ivector/global_cmvn.stats to /storage/emulated/0/Android/data/org.kaldi.demo/files/sync/model-android/ivector/global_cmvn.stats
2019-11-13 10:16:05.101 6011-6052/org.kaldi.demo I/Assets: Copying asset model-android/Gr.fst to /storage/emulated/0/Android/data/org.kaldi.demo/files/sync/model-android/Gr.fst
2019-11-13 10:16:05.101 6011-6052/org.kaldi.demo I/Assets: Copying asset model-android/ivector/online_cmvn.conf to /storage/emulated/0/Android/data/org.kaldi.demo/files/sync/model-android/ivector/online_cmvn.conf
2019-11-13 10:16:05.181 6011-6052/org.kaldi.demo I/Assets: Copying asset model-android/ivector/final.ie to /storage/emulated/0/Android/data/org.kaldi.demo/files/sync/model-android/ivector/final.ie
2019-11-13 10:16:05.301 6011-6052/org.kaldi.demo I/Assets: Copying asset model-android/final.mdl to /storage/emulated/0/Android/data/org.kaldi.demo/files/sync/model-android/final.mdl
2019-11-13 10:16:05.303 6011-6052/org.kaldi.demo D/!!!!: /storage/emulated/0/Android/data/org.kaldi.demo/files/sync
2019-11-13 10:16:05.303 6011-6052/org.kaldi.demo V/KaldiDemo: Sample rate is 16000
2019-11-13 10:16:05.317 6011-6052/org.kaldi.demo V/KaldiDemo: Computing derived variables for iVector extractor
    
    --------- beginning of crash
2019-11-13 10:16:05.317 6011-6052/org.kaldi.demo A/libc: Fatal signal 4 (SIGILL), code 2 (ILL_ILLOPN), fault addr 0x78ce5e3190f2 in tid 6052 (AsyncTask #1), pid 6011 (org.kaldi.demo)

```

**Comment by nshmyrev** [comment]
what is your cpu? it feels quite old.

**Comment by furtherout** [comment]
That print out was the emulator CPU info so it's virtual and based on the Android9 x86_64 image (non google however same result with the Google one). My host CPU is relatively new. 8th gen intel i7: Intel(R) Core(TM) i7-8550U running linux ubuntu 18.04.

Does it work for you on the emulator?

**Comment by nshmyrev** [comment]
Ok, emulator doesn't support sandybridge instruction set it seems. I'll recompile a bit later.

**Comment by nshmyrev** [comment]
I pushed commit d06b6380bfb7ed678b67c331f1f8617fda0ab05a, should be better now

**Comment by furtherout** [comment]
thanks I can confirm it is fixed

**Comment by gabriel-TheCode** [comment]
Please guys, I have the same problem. How did you correct it?
